on:
    push:
        branches:
            - main

jobs:
    precursor:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: precursor
              run: echo The username is ${{ inputs.username }}
