on:
    push:
        branches:
            - main

jobs:
    precursor:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: use precursor branch
              run: git checkout -B precursor
            - name: update branch content
              run: git reset --hard main
            - name: push upstream
              run: git push --set-upstream origin precursor
